/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package game_quest;

import Controller.KnightsTourProblemController;
import Model.KnightsTourProblemModel;
import View.KnightsTourProblemUI;
import View.TicTacToeView;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import View.IdentifyShortestPathView;
/**
 *
 * @author ndila
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        
        try {
            BufferedImage backgroundImg = ImageIO.read(getClass().getResource("/Images/MainMenu.png"));
            ImageIcon backgroundIcon = new ImageIcon(backgroundImg.getScaledInstance(1920, 1080, Image.SCALE_SMOOTH));
            lbl_background.setIcon(backgroundIcon);
            
            BufferedImage knighTourImg = ImageIO.read(getClass().getResource("/Images/game1.png"));
            ImageIcon knighTourIcon = new ImageIcon(knighTourImg.getScaledInstance(650, 80, Image.SCALE_SMOOTH));
            lbl_knightTour.setIcon(knighTourIcon);
            
            BufferedImage shortestPathImg = ImageIO.read(getClass().getResource("/Images/game2.png"));
            ImageIcon shortestPath = new ImageIcon(shortestPathImg.getScaledInstance(650, 80, Image.SCALE_SMOOTH));
            lbl_longest.setIcon(shortestPath);
            
            BufferedImage eightQueen = ImageIO.read(getClass().getResource("/Images/game3.png"));
            ImageIcon eightQueenIcon = new ImageIcon(eightQueen.getScaledInstance(650, 80, Image.SCALE_SMOOTH));
            lbl_eightQueen.setIcon(eightQueenIcon);
            
            BufferedImage ticTac = ImageIO.read(getClass().getResource("/Images/game4.png"));
            ImageIcon ticTacIcon = new ImageIcon(ticTac.getScaledInstance(650, 80, Image.SCALE_SMOOTH));
            lbl_ticTac.setIcon(ticTacIcon);
            
            BufferedImage shortest = ImageIO.read(getClass().getResource("/Images/game5.png"));
            ImageIcon shortestIcon = new ImageIcon(shortest.getScaledInstance(650, 80, Image.SCALE_SMOOTH));
            lbl_shotest.setIcon(shortestIcon);
            
            BufferedImage closeImage = ImageIO.read(getClass().getResource("/Images/closeIcon.png"));
            ImageIcon closedIcon = new ImageIcon(closeImage.getScaledInstance(60, 60, Image.SCALE_SMOOTH));
            lbl_close.setIcon(closedIcon);

        } catch (IOException e) {
            e.printStackTrace();
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_close = new javax.swing.JLabel();
        lbl_shotest = new javax.swing.JLabel();
        lbl_ticTac = new javax.swing.JLabel();
        lbl_eightQueen = new javax.swing.JLabel();
        lbl_longest = new javax.swing.JLabel();
        lbl_knightTour = new javax.swing.JLabel();
        lbl_background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_closeMouseClicked(evt);
            }
        });
        getContentPane().add(lbl_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1830, 30, -1, -1));

        lbl_shotest.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_shotest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_shotestMouseClicked(evt);
            }
        });
        getContentPane().add(lbl_shotest, new org.netbeans.lib.awtextra.AbsoluteConstraints(1063, 760, -1, -1));

        lbl_ticTac.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_ticTac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_ticTacMouseClicked(evt);
            }
        });
        getContentPane().add(lbl_ticTac, new org.netbeans.lib.awtextra.AbsoluteConstraints(1063, 630, -1, -1));

        lbl_eightQueen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_eightQueen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_eightQueenMouseClicked(evt);
            }
        });
        getContentPane().add(lbl_eightQueen, new org.netbeans.lib.awtextra.AbsoluteConstraints(1063, 500, -1, -1));

        lbl_longest.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_longest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_longestMouseClicked(evt);
            }
        });
        getContentPane().add(lbl_longest, new org.netbeans.lib.awtextra.AbsoluteConstraints(1063, 370, -1, -1));

        lbl_knightTour.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_knightTour.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_knightTourMouseClicked(evt);
            }
        });
        getContentPane().add(lbl_knightTour, new org.netbeans.lib.awtextra.AbsoluteConstraints(1063, 240, -1, -1));

        lbl_background.setMaximumSize(new java.awt.Dimension(1920, 1080));
        lbl_background.setMinimumSize(new java.awt.Dimension(1920, 1080));
        lbl_background.setPreferredSize(new java.awt.Dimension(1920, 1080));
        getContentPane().add(lbl_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_knightTourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_knightTourMouseClicked
        KnightsTourProblemController controller = new KnightsTourProblemController(8); // Initialize with the desired chessboard size
        KnightsTourProblemUI view = new KnightsTourProblemUI(controller);
        view.setVisible(true);
        this.setVisible(false);
        controller.getMetrixAnswer();
    }//GEN-LAST:event_lbl_knightTourMouseClicked

    private void lbl_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lbl_closeMouseClicked

    private void lbl_ticTacMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_ticTacMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        TicTacToeView ticView = new TicTacToeView();
        ticView.setVisible(true);
    }//GEN-LAST:event_lbl_ticTacMouseClicked

    private void lbl_shotestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_shotestMouseClicked
        // TODO add your handling code here:
        IdentifyShortestPathView shortest_path = new IdentifyShortestPathView();
        shortest_path.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lbl_shotestMouseClicked

    private void lbl_eightQueenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_eightQueenMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_eightQueenMouseClicked

    private void lbl_longestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_longestMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_longestMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MainMenu().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl_background;
    private javax.swing.JLabel lbl_close;
    private javax.swing.JLabel lbl_eightQueen;
    private javax.swing.JLabel lbl_knightTour;
    private javax.swing.JLabel lbl_longest;
    private javax.swing.JLabel lbl_shotest;
    private javax.swing.JLabel lbl_ticTac;
    // End of variables declaration//GEN-END:variables
}
