/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import javax.swing.JOptionPane;
import Controller.LCSController;
import Model.LCSModel;
import game_quest.MainMenu;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.SwingConstants;

/**
 *
 * @author risin
 */
public class LCSView extends javax.swing.JFrame {

    private String x, y;
    public String playerName;
    private LCSController controller;
    private String userResponse;
    
    
    
    public LCSView() {

        this.playerName = playerName;
        this.userResponse = userResponse;
        this.controller = new LCSController();
         initComponents();
        
        try {
            BufferedImage backgroundImg = ImageIO.read(getClass().getResource("/View/images/backgroundImg.png"));
            ImageIcon backgroundIcon = new ImageIcon(backgroundImg.getScaledInstance(900, 800, Image.SCALE_SMOOTH));
            lbl_bg.setIcon(backgroundIcon);

        } catch (IOException e) {
            e.printStackTrace();
        }
        
        lbl_string1.setHorizontalTextPosition(SwingConstants.CENTER);
        lbl_string1.setVerticalTextPosition(SwingConstants.CENTER);
        lbl_string2.setHorizontalTextPosition(SwingConstants.CENTER);
        lbl_string2.setVerticalTextPosition(SwingConstants.CENTER);
        
        btn_check.setOpaque(false);
        btn_check.setContentAreaFilled(false);
        btn_check.setBorderPainted(false);
    }
    public void setstring(){
        x = controller.generateRandomString().toUpperCase();
        y = controller.generateRandomString().toUpperCase();
        lbl_string1.setText(x);
        lbl_string2.setText(y);
        txt_answer.setText("");
         
    }
     
    public void showMessage(String message) {

        JOptionPane.showMessageDialog(this, message);

    }
    
    public void showPlayer(){
        do{ playerName = JOptionPane.showInputDialog(this,"Enter Player's Name:");
           if(playerName == null || playerName.isEmpty()){
                   showMessage("Player name can't be empty. Please enter a valid name.");
                   
           }
           else{
                   showMessage("Player Name: "+playerName);
                   lbl_player.setText("Player Name: " +playerName);
           }
          }
        while(playerName == null || playerName.isEmpty());
       }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_string1 = new javax.swing.JLabel();
        lbl_string2 = new javax.swing.JLabel();
        btn_check = new javax.swing.JButton();
        txt_answer = new javax.swing.JTextField();
        lbl_name = new javax.swing.JLabel();
        lbl_home = new javax.swing.JLabel();
        lbl_close = new javax.swing.JLabel();
        lbl_player = new javax.swing.JLabel();
        lbl_bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 800));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(900, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_string1.setBackground(new java.awt.Color(255, 255, 255));
        lbl_string1.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        lbl_string1.setForeground(new java.awt.Color(0, 0, 153));
        lbl_string1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_string1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/images/wordBackground.png"))); // NOI18N
        lbl_string1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl_string1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(lbl_string1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, 259, 45));
        lbl_string1.getAccessibleContext().setAccessibleDescription("");

        lbl_string2.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        lbl_string2.setForeground(new java.awt.Color(0, 0, 153));
        lbl_string2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_string2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/images/wordBackground.png"))); // NOI18N
        lbl_string2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lbl_string2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 410, 259, 45));

        btn_check.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btn_check.setForeground(new java.awt.Color(242, 242, 242));
        btn_check.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/images/play.png"))); // NOI18N
        btn_check.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        btn_check.setBorderPainted(false);
        btn_check.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_check.setFocusPainted(false);
        btn_check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_checkActionPerformed(evt);
            }
        });
        getContentPane().add(btn_check, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 650, 160, 60));

        txt_answer.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txt_answer.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_answer.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, null, new java.awt.Color(102, 102, 102)));
        getContentPane().add(txt_answer, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 520, 550, 42));

        lbl_name.setFont(new java.awt.Font("Showcard Gothic", 3, 48)); // NOI18N
        lbl_name.setForeground(new java.awt.Color(255, 255, 255));
        lbl_name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_name.setText("Longest Common Sequence");
        getContentPane().add(lbl_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 800, 100));

        lbl_home.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/images/homeLCS.png"))); // NOI18N
        lbl_home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_home.setRequestFocusEnabled(false);
        lbl_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_homeMouseClicked(evt);
            }
        });
        getContentPane().add(lbl_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 20, -1, -1));

        lbl_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/images/closeLCS.png"))); // NOI18N
        lbl_close.setText("jLabel1");
        lbl_close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_closeMouseClicked(evt);
            }
        });
        getContentPane().add(lbl_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 20, 70, -1));

        lbl_player.setFont(new java.awt.Font("Copperplate Gothic Bold", 3, 24)); // NOI18N
        lbl_player.setForeground(new java.awt.Color(0, 255, 255));
        lbl_player.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_player.setPreferredSize(new java.awt.Dimension(200, 34));
        getContentPane().add(lbl_player, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 450, 50));

        lbl_bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/images/backgroundImg.png"))); // NOI18N
        getContentPane().add(lbl_bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_checkActionPerformed
        String userAnswer  = txt_answer.getText();
        String correctAnswer  = controller.calculateLCS(x, y);
        
        if(!userAnswer.equals(userAnswer.toUpperCase())){
            showMessage("Answer must be in capital letters only.");
            return;
        }
        
        System.out.println("Correct: "+correctAnswer);
        System.out.println("User: "+userAnswer);
        
        if(userAnswer.equals(correctAnswer)){
            showMessage("You win!");
            LCSModel lcsmodel = new LCSModel(this); //Pass the current instance of LCSView
            lcsmodel.savePlayerInfo(userAnswer);
        }
        else{
            showMessage("You lose. Try again!");
        }
        x = controller.generateRandomString();
        y = controller.generateRandomString();
        lbl_string1.setText(x);
        lbl_string2.setText(y);
        txt_answer.setText("");
    }//GEN-LAST:event_btn_checkActionPerformed

    private void lbl_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_closeMouseClicked
            
        // Handle the click event here
            int option = JOptionPane.showConfirmDialog(
            LCSView.this, 
            "Are you sure you want to exit the game?",
            "Close Confirmation",
            JOptionPane.YES_NO_OPTION
        );
            
            if (option == JOptionPane.YES_OPTION) {
            // User confirmed, close the entire application
            System.exit(0);
        }
    }//GEN-LAST:event_lbl_closeMouseClicked

    private void lbl_homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_homeMouseClicked
        MainMenu menu =  new MainMenu();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lbl_homeMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(LCSView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(LCSView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(LCSView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(LCSView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new LCSView().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_check;
    private javax.swing.JLabel lbl_bg;
    private javax.swing.JLabel lbl_close;
    private javax.swing.JLabel lbl_home;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_player;
    private javax.swing.JLabel lbl_string1;
    private javax.swing.JLabel lbl_string2;
    private javax.swing.JTextField txt_answer;
    // End of variables declaration//GEN-END:variables
}
