/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author Lakshan
 */

import Controller.TicTacToeController;
import Model.TicTacToeModel;
import javax.swing.*;
import javax.swing.BorderFactory;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import CustomFonts.CustomFonts;
import game_quest.MainMenu;
        

public class TicTacToeView extends javax.swing.JFrame implements ActionListener {
    
    private static final int boardSize = 3;
    private static final char humanPlayer = 'X';
    private static final char aiPlayer = 'O';
    private static final char Enull = '-';
    String playerName;

    /**
     * Creates new form TicTacToeView
     */
    
    private JPanel chessboardPanel;
    private JButton[][] buttons;
    private TicTacToeController game;
    private TicTacToeModel model;
    public CustomFonts cus_font = new CustomFonts();
    
    public TicTacToeView() {
        initComponents();
        setLocationRelativeTo(null);
        model = new TicTacToeModel();
        game=new TicTacToeController();        
        setTitle("Tic Tac Toe");
        chessboardPanel = new JPanel(new GridLayout(boardSize, boardSize));
        buttons = new JButton[boardSize][boardSize];
       
        for (int i = 0; i < boardSize; i++) {
            for (int j = 0; j < boardSize; j++) {
                buttons[i][j] = new JButton();
                buttons[i][j].setBackground(Color.WHITE); // Set background color
                buttons[i][j].setBackground(Color.decode("#BE8452"));//864D27 BE8452 985f36
                buttons[i][j].setFont(cus_font.Woodlook(80));
                buttons[i][j].setForeground(Color.decode("#603114"));
                buttons[i][j].setFocusPainted(false); // Remove button border
                //buttons[i][j].setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10)); // Add padding
                buttons[i][j].setBorder(BorderFactory.createLineBorder(Color.decode("#78401E"), 2));
                chessboardPanel.add(buttons[i][j]);
                buttons[i][j].addActionListener(this);
                
            }
        }
        board_panel.setLayout(new BorderLayout());
        board_panel.add(chessboardPanel, BorderLayout.CENTER);
        setVisible(true);
        playerName();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        board_panel = new javax.swing.JPanel();
        lbl_playerName = new javax.swing.JLabel();
        reset_btn = new javax.swing.JLabel();
        home_btn = new javax.swing.JLabel();
        close_btn = new javax.swing.JLabel();
        panel_background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(700, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        board_panel.setBackground(new java.awt.Color(120, 64, 30));
        board_panel.setMinimumSize(new java.awt.Dimension(500, 500));
        board_panel.setPreferredSize(new java.awt.Dimension(400, 400));
        board_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(board_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, -1, -1));
        getContentPane().add(lbl_playerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 260, -1));

        reset_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tictactoe_reset_btn.png"))); // NOI18N
        reset_btn.setText("jLabel1");
        reset_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reset_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reset_btnMouseClicked(evt);
            }
        });
        getContentPane().add(reset_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 700, 240, -1));

        home_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tictactoe_home_btn.png"))); // NOI18N
        home_btn.setText("jLabel1");
        home_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        home_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                home_btnMouseClicked(evt);
            }
        });
        getContentPane().add(home_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 70, 80));

        close_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tictactoe_close_btn.png"))); // NOI18N
        close_btn.setText("jLabel1");
        close_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                close_btnMouseClicked(evt);
            }
        });
        getContentPane().add(close_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 0, 70, 80));

        panel_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/tictactoe_wooden_background.jpg"))); // NOI18N
        panel_background.setText("jLabel1");
        panel_background.setMaximumSize(new java.awt.Dimension(700, 800));
        panel_background.setMinimumSize(new java.awt.Dimension(700, 800));
        panel_background.setPreferredSize(new java.awt.Dimension(700, 800));
        getContentPane().add(panel_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void close_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_close_btnMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_close_btnMouseClicked

    private void reset_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reset_btnMouseClicked
        // TODO add your handling code here:
        resetBoard();
    }//GEN-LAST:event_reset_btnMouseClicked

    private void home_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_btnMouseClicked
        // TODO add your handling code here:
        MainMenu menu =  new MainMenu();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_home_btnMouseClicked
    
    @Override
    public void actionPerformed(ActionEvent e){
    
     JButton button = (JButton) e.getSource();
     for (int i = 0; i < boardSize; i++) {
            for (int j = 0; j < boardSize; j++) {
     if (button == buttons[i][j] && game.isMoveValid(i, j) && !game.isGameOver()) {
                    game.makeMove(i, j, humanPlayer);
                    button.setText(Character.toString(humanPlayer));
                    
                    if (!game.isGameOver()) {
                        game.makeAIMove();
                        int computerRow = game.getComputerMoveRow();
                        int computerCol = game.getComputerMoveCol();
                        buttons[computerRow][computerCol].setText(Character.toString(aiPlayer));
                    }

                    if (game.isGameOver()) {
                        if (game.checkForWin(humanPlayer)) {
                            game.printBoard(); //if win send this to db
                            JOptionPane.showMessageDialog(this, "You've won the game.","Congratulations!",JOptionPane.INFORMATION_MESSAGE);
                        } 
                        else if (game.checkForWin(aiPlayer)) {
                            String matrixAnswer = game.getMatrixAnswer();
                            System.out.println(matrixAnswer);
                            JOptionPane.showMessageDialog(this, "Better luck next time.","You lost!",JOptionPane.ERROR_MESSAGE);
                            //String playerName = JOptionPane.showInputDialog(this, "Enter your name:");
                            model.savePlayerResponse(playerName, matrixAnswer);
                        } 
                        else {
                            JOptionPane.showMessageDialog(this, "It's a Draw, the game is tied.","Try Again!",JOptionPane.WARNING_MESSAGE);
                        }
                        resetBoard();
                    }
                }
            }
        
     }
    
    }
    
    public void resetBoard() {
        game = new TicTacToeController();
        for (int i = 0; i < boardSize; i++) {
            for (int j = 0; j < boardSize; j++) {
                buttons[i][j].setText("");
                buttons[i][j].setEnabled(true); // Re-enable buttons
            }
        }
    }
    
    /*public void getPlayerName() {
        while (true) {
            JTextField nameField = new JTextField();
            JComponent[] inputs = new JComponent[]{
                new JLabel("Enter your name:"),
                nameField
            };

            int result = JOptionPane.showOptionDialog( null, inputs, "Player Name",
                JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                new String[]{"Start", "Exit"}, // Button labels
                "Start" // Default button
            );
            result.setInitialValue(null);

            if (result == JOptionPane.OK_OPTION) {
                playerName = nameField.getText();
                if (playerName.isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Name should be entered to start!", "Error", JOptionPane.ERROR_MESSAGE);
                }
                else if (!playerName.matches("^[a-zA-Z ]+$")) {
                    JOptionPane.showMessageDialog(null, "Name should contain only alphabet characters!", "Error", JOptionPane.ERROR_MESSAGE);
                }
                else {
                    lbl_playerName.setFont(cus_font.komikz(20));
                    lbl_playerName.setText("Player Name: " + playerName);
                    //System.out.println("Player Name: " + playerName);
                    break; 
                }
            } else {
                System.out.println("User canceled the input.");
                System.exit(0); 
            }
        }
    }*/
    
    private void playerName() {
        while (true) {
            JTextField nameField = new JTextField();
            JComponent[] inputs = new JComponent[]{new JLabel("Enter your name:"), nameField};

            JOptionPane optionPane = new JOptionPane(inputs, JOptionPane.QUESTION_MESSAGE, JOptionPane.OK_CANCEL_OPTION, null, new String[]{"Start", "Exit"}, "Start");
            optionPane.setInitialValue(null); // This line sets the initial focus on the text box

            JDialog dialog = optionPane.createDialog("Player Name");
            dialog.setVisible(true);

            Object selectedValue = optionPane.getValue();

            if ("Start".equals(selectedValue)) {
                playerName = nameField.getText();
                if (playerName.isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Name should be entered to start!", "Error", JOptionPane.ERROR_MESSAGE);
                } else if (!playerName.matches("^[a-zA-Z ]+$")) {
                    JOptionPane.showMessageDialog(null, "Name should contain only alphabet characters!", "Error", JOptionPane.ERROR_MESSAGE);
                } else {
                    lbl_playerName.setFont(cus_font.komikz(25));
                    lbl_playerName.setForeground(Color.white);
                    lbl_playerName.setText(playerName);
                    lbl_playerName.setHorizontalAlignment(SwingConstants.CENTER);
                    break;
                }
            } else {
                System.out.println("User canceled the input.");
                System.exit(0);
            }
        }
    }

    
   /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicTacToeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicTacToeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicTacToeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicTacToeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               //new TicTacToeView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel board_panel;
    private javax.swing.JLabel close_btn;
    private javax.swing.JLabel home_btn;
    private javax.swing.JLabel lbl_playerName;
    private javax.swing.JLabel panel_background;
    private javax.swing.JLabel reset_btn;
    // End of variables declaration//GEN-END:variables
}
